name             'wmongodb'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures wmongodb'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.5'

#depends 'apt', '~>2.3.8'
#depends 'build-essential', '~>2.0.0'
#depends 'chef_handler', '~>1.1.6'
#depends 'dmg', '~>2.2.0'
#depends 'git', '~>4.0.0'
#depends 'mongodb', '~> 0.15.0'
#depends 'monit', '~>1.0.0'
#depends 'python', '~>1.4.6'
#depends 'runit', '~>1.5.10'
#depends 'windows', '~>1.30.2'
#depends 'yum', '~>3.2.0'
#depends 'yum-epel', '~>0.3.6'

depends 'apt'
depends 'build-essential'
depends 'chef_handler'
depends 'dmg'
depends 'git'
depends 'mongodb'
depends 'monit'
depends 'python'
depends 'runit'
depends 'windows'
depends 'yum'
depends 'yum-epel'
